xia-framework:
xia-module:
xia-module-pypi:
xia-module-terraform-gcs:
xia-module-gcp-project:
xia-module-application-gh:
xia-module-gcp-bigquery:
xia-demo-framework-01:
action-gcs-terraform-apply:
  template_name: xia-template-action