xia-module:
  package: xia-module
  class: Module
gh-module-application:
  package: xia-module-application-gh
  class: Application
  events:
    deploy:
gcp-module-project:
  package: xia-module-gcp-project
  class: Project
  events:
    deploy:
module-state-gcs:
  package: xia-module-terraform-gcs
  class: GcsState
  events:
    activate:
gcp-module-pypi:
  package: xia-module-pypi
  class: PypiGcp
  events:
    activate:
module-pypi:
  package: xia-module-pypi
  class: Pypi
  events:
    activate:
gcp-module-dataset:
  package: xia-module-gcp-bigquery
  class: Dataset
  events:
    activate:
gcp-module-table:
  package: xia-module-gcp-bigquery
  class: Table
  events:
    activate:
