xia_module:
  package: xia-module
  class: Module
  git_https: github.com/x-i-a/xia-module
gh_module_application:
  package: xia-module-application-gh
  class: Application
  git_https: github.com/x-i-a/xia-module-application-gh
  events:
    deploy:
gcp_module_project:
  package: xia-module-gcp-project
  class: Project
  git_https: github.com/x-i-a/xia-module-gcp-project
  events:
    deploy:
gcp_module_pypi:
  package: xia-module-pypi
  class: PypiGcp
  events:
    activate:
module_pypi:
  package: xia-module-pypi
  class: Pypi
  events:
    activate:
gcp_module_dataset:
  package: xia-module-gcp-bigquery
  class: Dataset
  events:
    activate:
gcp_module_table:
  package: xia-module-gcp-bigquery
  class: Table
  events:
    activate:
