name: Workflow - dev

on:
  push:
    branches:
    - main

jobs:
  deploy:
    if: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - id: prepare-modules
      name: Prepare modules
      run: |
        pip install xia-framework xia-module
        python -m xia_framework.foundation plan

    - id: auth-gcp-oidc
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ vars.PROJECT_ID }}
        workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
        service_account: ${{ vars.PROVIDER_SA_EMAIL }}

    - id: auth-gcp-check
      shell: bash
      run: |
        cat $GOOGLE_APPLICATION_CREDENTIALS

    - id: terraform-apply
      name: Apply Terraform
      uses: x-i-a/action-gcs-terraform-apply@main
      env:
        GITHUB_TOKEN: ${{ secrets.FOUNDATION_GITHUB_TOKEN }}
      with:
        tf_bucket_name: ${{ vars.tf_bucket_name }}
        cosmos_name: ${{ vars.COSMOS_NAME }}
        realm_name: ${{ vars.REALM_NAME }}
        foundation_name: ${{ vars.FOUNDATION_NAME }}
